---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myfirstwebapp-argo
spec:
  project: default
  source:
    repoURL: 
    targetRevision: HEAD
    path: https://source.cloud.google.com/test-project-bodhi/mfwa-infra/+/main:
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false