apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myfirstwebapp-argo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://source.cloud.google.com/test-project-bodhi/mfwa-infra/'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
